[tickers]
# List of symbols to fetch. Empty [] to use symbols from Excel sheet.
symbols = ["MSFT", "AAPL", "TSLA", "XRP"]
days_history = 100 

[files]
excel = "mbook3.xlsx"
db = "stocks.db"

[predictor]
# Parameters for prediction algorithm (e.g., KalmanFilter).
lib_path = "./kalman_filter.so"
